home.search_box=id=twotabsearchtextbox
home.search_button=id=nav-search-submit-button

search.first_product=xpath=(//div[@data-component-type='s-search-result'])[1]//h2

product.price=xpath=(//span[contains(@class,'a-price-whole')])[1]

product.add_to_cart=id=add-to-cart-button